In [2]:
from numpy import *
from matplotlib import pyplot as plt

In [208]:
t = 1
g = 50
R = 1/sqrt(2)
theta = [-pi/8, pi/8, pi/4, 3*pi/8, -3*pi/8, pi/4+arctan(g/2), -pi/4, pi/4, pi/4+arctan(g/2), pi/4-arctan(g/2), -pi/4-arctan(g/2), pi/4, 0, 0]
theta2 = [0,0,pi/2,pi/2,pi/2,0,0,0,pi/2,pi/2,pi/2,0,0,0]

In [209]:
A = matrix([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
           [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
           [0, 0, 0, t, t, 0, t, -t, 0, 0, 0, 0, 0, 0],
           [0, 0, t, 0, 0, -t, 0, 0, 0, 0, 0, 0, 0, 0],
           [0, 0, t, 0, 0, t, 0, 0, 0, 0, 0, 0, 0, 0],
           [0, 0, 0, -t, t, 0, -t, -t, 0, 0, 0, 0, 0, 0],
           [0, 0, t, 0, 0, -t, 0, 0, 0, 0, 0, 0, 0, 0],
           [0, 0, -t, 0, 0, -t, 0, 0, 0, 0, 0, 0, 0, 0],
           [0, 0, 0, 0, 0, 0, 0, 0, 0, t, t, 0, t, -t],
           [0, 0, 0, 0, 0, 0, 0, 0, t, 0, 0, -t, 0, 0],
           [0, 0, 0, 0, 0, 0, 0, 0, t, 0, 0, -t, 0, 0],
           [0, 0, 0, 0, 0, 0, 0, 0, 0, -t, t, 0, -t, -t],
           [0, 0, 0, 0, 0, 0, 0, 0, t, 0, 0, -t, 0, 0],
           [0, 0, 0, 0, 0, 0, 0, 0, -t, 0, 0, -t, 0, 0]])

In [210]:
B = matrix([[R, 0, 0, -R, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
           [0, R, 0, 0, R, 0, 0, 0, 0, 0, 0, 0, 0, 0],
           [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
           [R, 0, 0, R, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
           [0, R, 0, 0, R, 0, 0, 0, 0, 0, 0, 0, 0, 0],
           [0, 0, 0, 0, 0, R, 0, 0, -R, 0, 0, 0, 0, 0],
           [0, 0, 0, 0, 0, 0, R, 0, 0, -R, 0, 0, 0, 0],
           [0, 0, 0, 0, 0, 0, 0, R, 0, 0, -R, 0, 0, 0],
           [0, 0, 0, 0, 0, R, 0, 0, R, 0, 0, 0, 0, 0],
           [0, 0, 0, 0, 0, 0, R, 0, 0, R, 0, 0, 0, 0],
           [0, 0, 0, 0, 0, 0, 0, R, 0, 0, R, 0, 0, 0],
           [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
           [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
           [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [211]:
shape(theta)

(14,)

In [212]:
c = diag([cos(theta[0]),cos(theta[1]),cos(theta[2]),cos(theta[3]),cos(theta[4]),cos(theta[5]),cos(theta[6]),cos(theta[7]),cos(theta[8]),cos(theta[9]),cos(theta[10]),cos(theta[11]),cos(theta[12]),cos(theta[13])])
s = diag([sin(theta[0]),sin(theta[1]),sin(theta[2]),sin(theta[3]),sin(theta[4]),sin(theta[5]),sin(theta[6]),sin(theta[7]),sin(theta[8]),sin(theta[9]),sin(theta[10]),sin(theta[11]),sin(theta[12]),sin(theta[13])])
c2 = diag([cos(theta2[0]),cos(theta2[1]),cos(theta2[2]),cos(theta2[3]),cos(theta2[4]),cos(theta2[5]),cos(theta2[6]),cos(theta2[7]),cos(theta2[8]),cos(theta2[9]),cos(theta2[10]),cos(theta2[11]),cos(theta2[12]),cos(theta2[13])])
s2 = diag([sin(theta2[0]),sin(theta2[1]),sin(theta2[2]),sin(theta2[3]),sin(theta2[4]),sin(theta2[5]),sin(theta2[6]),sin(theta2[7]),sin(theta2[8]),sin(theta2[9]),sin(theta2[10]),sin(theta2[11]),sin(theta2[12]),sin(theta2[13])])

In [213]:
S_cz = block([[identity(14), 0*identity(14)],[A, identity(14)]])
S_bs = block([[B, 0*identity(14)],[0*identity(14), B]])
S_r = block([[c, s],[-s, c]])
S_r2 = block([[c2, s2],[-s2, c2]])

In [214]:
# S = matmul(S_r,matmul(S_r2,matmul(S_bs, S_cz)))
S = matmul(S_r,matmul(S_bs, S_cz))

In [215]:
S

matrix([[ 0.65328148,  0.        ,  0.27059805, -0.65328148,  0.        ,
         -0.27059805,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        , -0.27059805,
          0.        ,  0.        ,  0.27059805,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.65328148,  0.27059805,  0.        ,  0.65328148,
          0.27059805,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.27059805,  0.        ,  0.        ,  0.27059805,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.70710678,  0.70710678,  0.70710678,
          0.        ,  0.70710678, -0.70710678,  0.        ,  0.        ,
          0.  

In [216]:
U = S[0:12,2:14]
V = block([S[0:12,0:2], S[0:12,14:]])
Y = block([[S[13:15, 2:14]],[S[26:,2:14]]])
Z = block([[S[13:15,:2],S[13:15,14:]],[S[26:,:2],S[26:,14:]]])

In [217]:
M = Z - matmul(Y,matmul(linalg.inv(U),V))

In [218]:
test = linalg.inv(U)

In [221]:
test

matrix([[ 2.79001283e-01,  5.36967029e-02,  1.33431001e+00,
         -2.48268066e-01, -2.73745937e-01, -3.68635716e-02,
         -4.06579464e-01,  2.04716408e-01, -6.86183597e-03,
         -9.92881137e-01, -3.46718573e-01,  4.00419562e-17],
        [-1.30656296e+00, -3.66343075e-17, -3.62601160e-17,
          5.41196100e-01, -7.38396471e-17,  2.80814733e-17,
          1.38707677e-16, -1.19292161e-16,  1.31537370e-17,
          1.18405740e-16,  1.63056293e-16, -1.13940118e-32],
        [ 4.05743973e-02,  2.59270617e-01,  6.44261864e+00,
         -4.35306629e+00,  2.37375582e+00, -1.77993069e-01,
         -1.96313931e+00,  9.88458255e-01, -3.31318749e-02,
         -4.79405421e+00, -1.67410536e+00,  1.93339667e-16],
        [-2.62194817e-01,  5.36967029e-02,  1.33431001e+00,
         -1.55483103e+00, -2.73745937e-01, -3.68635716e-02,
         -4.06579464e-01,  2.04716408e-01, -6.86183597e-03,
         -9.92881137e-01, -3.46718573e-01,  4.00419562e-17],
        [ 6.14833346e-01,  1.0209980

In [220]:
M[:4,:4]

matrix([[-3.76211542e+14, -1.15677743e+15, -2.14846940e+15,
          5.80242525e+14],
        [ 5.41196100e-01, -4.50467236e-17,  1.30656296e+00,
         -2.95476815e-17],
        [ 8.00000000e+00,  2.80000000e+01,  8.00000000e+00,
         -2.40000000e+01],
        [ 1.95630002e+16,  6.01524263e+16,  1.11720409e+17,
         -3.01726113e+16]])

In [132]:
%matplotlib qt
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')

x3 = [1,1,1,1,2,2,2,2,3,3,3,3,4,4,4,4]
y3 = [1,2,3,4,1,2,3,4,1,2,3,4,1,2,3,4]
z3 = zeros(16)

dx = ones(16)
dy = ones(16)
dz = [M[x3[i]-1,y3[i]-1] for i in range(16)]

ax.bar3d(x3, y3, z3, dx, dy, dz, shade=True)

# ax.bar3d(x, y, bottom, width, depth, top, shade=True)

In [175]:
linalg.inv(U)

LinAlgError: Singular matrix